# frpc configuration for N1
serverAddr = "38.14.254.183"
serverPort = 7000
token = "315600"

[[proxies]]
name = "n1_web"
type = "http"
localPort = 80
customDomains = ["ys.315600.xyz"]

[[proxies]]
name = "n1_ssh"
type = "tcp"
localIP = "127.0.0.1"
localPort = 22
remotePort = 2222
